Add Windows to cibuild

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -178,78 +178,10 @@ jobs:
       - name: Test
         run: |
           pytest tests
-
-  build-windows:
-    name: "Build Windows ${{matrix.config.arch}} py-${{ matrix.config.python }} ${{matrix.config.os}}"
-    if: startsWith(github.ref, 'refs/tags')
-    needs: [build-deps-windows]
-    runs-on: ${{ matrix.config.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        config:
-          - {os: windows-latest, python: "3.6", arch: win32, py-arch: x86}
-          - {os: windows-latest, python: "3.7", arch: win32, py-arch: x86}
-          - {os: windows-latest, python: "3.8", arch: win32, py-arch: x86}
-          - {os: windows-latest, python: "3.9", arch: win32, py-arch: x86}
-          - {os: windows-latest, python: "3.10", arch: win32, py-arch: x86}
-          - {os: windows-latest, python: "3.6", arch: x64, py-arch: x64}
-          - {os: windows-latest, python: "3.7", arch: x64, py-arch: x64}
-          - {os: windows-latest, python: "3.8", arch: x64, py-arch: x64}
-          - {os: windows-latest, python: "3.9", arch: x64, py-arch: x64}
-          - {os: windows-latest, python: "3.10", arch: x64, py-arch: x64}
-
-    steps:
-      - uses: actions/checkout@v3
-        name: Checkout
-
-      - name: Cache Headers
-        id: cache-headers
-        uses: actions/cache@v3
-        with:
-          path: Include
-          key: "Include-${{ env.CACHE_KEY }}"
-          
-      - name: Cache Libs
-        id: cache-libs
-        uses: actions/cache@v3
-        with:
-          path: libs
-          key: "libs-${{ matrix.config.arch }}-${{ env.CACHE_KEY}}"
-
-      - name: Retrieve Headers
-        if: steps.cache-headers.outputs.cache-hit != 'true'
-        run: exit 1
-          
-      - name: Retrieve Libs
-        if: steps.cache-libs.outputs.cache-hit != 'true'
-        run: exit 1
-
-      - name: Install Python
-        uses: actions/setup-python@v2
-        with:
-          architecture: ${{ matrix.config.py-arch }}
-          python-version: ${{ matrix.config.python }}
-
-      - name: Build
-        run: |
-          pip install Cython wheel pytest
-          python setup.py bdist_wheel
-          pip uninstall cython -y
-          pip install $(ls dist)
-          
-      - name: Test
-        run: |
-          pytest tests
-
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: dist
-          path: dist/
           
   cibuildwheel:
     name: Build wheels on ${{ matrix.os }}  ${{ matrix.arch }}
+    needs: [build-deps-windows]
     if: startsWith(github.ref, 'refs/tags')
     runs-on: ${{ matrix.os }}
     strategy:
@@ -262,14 +194,16 @@ jobs:
             arch: i686
           - os: ubuntu-latest
             arch: x86_64
+          - os: windows-latest
+            arch: AMD64
+            win-arch: x64
+          - os: windows-latest
+            arch: x86
+            win-arch: win32
 #           - os: macos-latest
 #             arch: arm64
 #           - os: macos-latest
 #             arch: x86_64
-#           - os: windows-latest
-#             arch: AMD64
-#           - os: windows-latest
-#             arch: x86
 
     env:
       CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_24
@@ -279,9 +213,10 @@ jobs:
       CIBW_MANYLINUX_PPC64LE_IMAGE: manylinux_2_24
       CIBW_MANYLINUX_S390X_IMAGE: manylinux_2_24
       CIBW_ARCHS: ${{ matrix.arch }}
-      CIBW_BEFORE_BUILD: pip install cython
       CIBW_BEFORE_ALL_LINUX: script/cibuild.sh
-      CIBW_SKIP: pp* *-musllinux*
+      CIBW_BEFORE_BUILD: pip install cython
+      CIBW_ENVIRONMENT_WINDOWS: PYJERASURE_INCLUDE=D:\\a\\pyjerasure\\pyjerasure\\Include PYJERASURE_LIB=D:\\a\\pyjerasure\\pyjerasure\\libs
+      CIBW_SKIP: pp* *-musllinux_i686*
       CIBW_TEST_REQUIRES: pytest
       CIBW_TEST_COMMAND: pytest {project}/tests
     steps:
@@ -291,30 +226,36 @@ jobs:
       - name: Set up QEMU
         if: matrix.os == 'ubuntu-latest'
         uses: docker/setup-qemu-action@v1
-        
-#       - name: Cache Headers
-#         if: matrix.os == 'windows-latest'
-#         id: cache-headers
-#         uses: actions/cache@v3
-#         with:
-#           path: Include
-#           key: "Include-${{ env.CACHE_KEY }}"
-          
-#       - name: Cache Libs
-#         if: matrix.os == 'windows-latest'
-#         id: cache-libs
-#         uses: actions/cache@v3
-#         with:
-#           path: libs
-#           key: "libs-${{ matrix.config.arch }}-${{ env.CACHE_KEY}}"
 
-#       - name: Retrieve Headers
-#         if: matrix.os == 'windows-latest' && steps.cache-headers.outputs.cache-hit != 'true'
-#         run: exit 1
+      - name: Copy src
+        run: |
+          mkdir ../src
+          cp -r ./* ../src
+          mv ../src .
           
-#       - name: Retrieve Libs
-#         if: matrix.os == 'windows-latest' && steps.cache-libs.outputs.cache-hit != 'true'
-#         run: exit 1
+      - name: Windows Cache Headers
+        if: matrix.os == 'windows-latest'
+        id: cache-headers
+        uses: actions/cache@v3
+        with:
+          path: Include
+          key: "Include-${{ env.CACHE_KEY }}"
+          
+      - name: Windows Cache Libs
+        if: matrix.os == 'windows-latest'
+        id: cache-libs
+        uses: actions/cache@v3
+        with:
+          path: libs
+          key: "libs-${{ matrix.win-arch }}-${{ env.CACHE_KEY}}"
+
+      - name: Windows Retrieve Headers
+        if: matrix.os == 'windows-latest' && steps.cache-headers.outputs.cache-hit != 'true'
+        run: exit 1
+          
+      - name: Windows Retrieve Libs
+        if: matrix.os == 'windows-latest' && steps.cache-libs.outputs.cache-hit != 'true'
+        run: exit 1
 
       - name: Setup Python
         uses: actions/setup-python@v2
@@ -323,7 +264,7 @@ jobs:
         run: |
           python -m pip install cibuildwheel
       - name: Build wheels
-        run: python -m cibuildwheel --output-dir dist
+        run: python -m cibuildwheel src --output-dir dist
         
       - name: Upload Artifact
         uses: actions/upload-artifact@v3
@@ -333,7 +274,7 @@ jobs:
 
   publish:
     runs-on: ubuntu-latest
-    needs: [sdist, cibuildwheel, build-windows, test-linux]
+    needs: [sdist, cibuildwheel, test-linux]
     if: startsWith(github.ref, 'refs/tags')
     steps:
       - name: Download Wheels
@@ -365,3 +306,72 @@ jobs:
 #         with:
 #           name: dist
 #           path: dist/*-manylinux*.whl
+
+#   build-windows:
+#     name: "Build Windows ${{matrix.config.arch}} py-${{ matrix.config.python }} ${{matrix.config.os}}"
+#     if: startsWith(github.ref, 'refs/tags')
+#     needs: [build-deps-windows]
+#     runs-on: ${{ matrix.config.os }}
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         config:
+#           - {os: windows-latest, python: "3.6", arch: win32, py-arch: x86}
+#           - {os: windows-latest, python: "3.7", arch: win32, py-arch: x86}
+#           - {os: windows-latest, python: "3.8", arch: win32, py-arch: x86}
+#           - {os: windows-latest, python: "3.9", arch: win32, py-arch: x86}
+#           - {os: windows-latest, python: "3.10", arch: win32, py-arch: x86}
+#           - {os: windows-latest, python: "3.6", arch: x64, py-arch: x64}
+#           - {os: windows-latest, python: "3.7", arch: x64, py-arch: x64}
+#           - {os: windows-latest, python: "3.8", arch: x64, py-arch: x64}
+#           - {os: windows-latest, python: "3.9", arch: x64, py-arch: x64}
+#           - {os: windows-latest, python: "3.10", arch: x64, py-arch: x64}
+
+#     steps:
+#       - uses: actions/checkout@v3
+#         name: Checkout
+
+#       - name: Cache Headers
+#         id: cache-headers
+#         uses: actions/cache@v3
+#         with:
+#           path: Include
+#           key: "Include-${{ env.CACHE_KEY }}"
+          
+#       - name: Cache Libs
+#         id: cache-libs
+#         uses: actions/cache@v3
+#         with:
+#           path: libs
+#           key: "libs-${{ matrix.config.arch }}-${{ env.CACHE_KEY}}"
+
+#       - name: Retrieve Headers
+#         if: steps.cache-headers.outputs.cache-hit != 'true'
+#         run: exit 1
+          
+#       - name: Retrieve Libs
+#         if: steps.cache-libs.outputs.cache-hit != 'true'
+#         run: exit 1
+
+#       - name: Install Python
+#         uses: actions/setup-python@v2
+#         with:
+#           architecture: ${{ matrix.config.py-arch }}
+#           python-version: ${{ matrix.config.python }}
+
+#       - name: Build
+#         run: |
+#           pip install Cython wheel pytest
+#           python setup.py bdist_wheel
+#           pip uninstall cython -y
+#           pip install $(ls dist)
+          
+#       - name: Test
+#         run: |
+#           pytest tests
+
+#       - name: Upload Artifact
+#         uses: actions/upload-artifact@v3
+#         with:
+#           name: dist
+#           path: dist/
